### PR TITLE
Add docstring

### PR DESCRIPTION
**Pull request by jsy0404**
Add docstring

### CODE REVIEW

**Comment by whgusqls007** [comment]
You are who offered us to use Codacy tho... :(

**Comment by khw1234** [comment]
i am so impreesed with your code man~

**Review by whgusqls007 — APPROVED** [review]

**Review by khw1234 — APPROVED** [review]

**Review by whgusqls007 — APPROVED** [review]

**Review by khw1234 — APPROVED** [review]

**Review by whgusqls007 — APPROVED** [review]

**Review by khw1234 — APPROVED** [review]

**Review by whgusqls007 — COMMENTED** [review]
I did review ㅡㅡ

**Review by khw1234 — COMMENTED** [review]
123

**Review by khw1234 — APPROVED** [review]
123

**Review by whgusqls007 — COMMENTED** [review]
??

**Pull request merged**
